### ISSUE TITLE
log verbosity should be dynamically changeable

### ISSUE THREAD

**Issue by msegura** [scality/werelogs#87]
Log verbosity is currently controlled by a static configuration file.

There is a need to be able to change to change the log verbosity without having to restart the daemon.

Having to restart mission critical service to investigate a problem is a major operational pain. When this is happening, we are already in a position where our negocation power with the customer is limited.

**Comment by DavidPineauScality** [comment]
The design was made taking that need into account.

As you can see the Config object is global and unique, and the various loggers refer to it (or temporarily copy its values for the RequestLogger).

The thing is that you need a way in the host component's code to update it dynamically, and that should be quick if it's only to address the logging configuration :)

**Comment by DavidPineauScality** [comment]
Sorry, I didn't explain myself well enough.

To "update the configuration", you can use one of your logger's `setLevel()` and `setDumpThreshold()` methods (https://github.com/scality/werelogs/blob/659d908f89b96e53096f9a8a136bdfff89339597/lib/Logger.js#L44)

It calls upon the global logging Config object, and updates its internal values, thus spreading its effects to all ModuleLoggers, and all future Request Loggers.
The RequestLoggers, them, copy the values from the config at the time of their creation, so only new RequestLoggers will take into account the updated configuration.

**Comment by msegura** [comment]
@DavidPineauScality thank you
